name = "RandomLogos"
uuid = "ae2b3ca2-baa9-4ff5-b4d2-d3fa2d2d37cc"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
